Import('env')

env["CPPPATH"] += [
    Dir("#/linux/include/"),
]

sources = [
    "clip.c",
    "fakewire_link.c",
    "platform.c",
    "semaphore.c",
]

objects = [env.Object(source) for source in sources]

objects += [
    "data.ld",
]

Return('objects')
