Import('env')

env["CPPPATH"] += [
    Dir("#/vivid/include/"),
]

env["VIVID_LINKSCRIPT"] = File('link.ld')
env["REPLICA_SCRIPT"] = File('replica.ld')

sources = [
    "clip.c",
    "clip_entry.s",
    "crash.c",
    "entrypoint.s",
    "fakewire_link.c",
    "gic.c",
    "idle.c",
    "scrubber.c",
    "startup.c",
    "tasks.c",
    "virtio_console.c",
    "virtio_device.c",
    "virtio_input.c",
    "virtio_output.c",
    "watchdog.c",
]

objects = [env.Object(source) for source in sources]

Return('objects')
