Import('env')

env["CPPPATH"] += [
    Dir("#/vivid/include/"),
]

env["VIVID_LINKSCRIPT"] = File('link.ld')
env["REPLICA_SCRIPT"] = File('replica.ld')

sources = [
    "abort.c",
    "crash.c",
    "entrypoint.s",
    "fakewire_link.c",
    "gic.c",
    "rtos_port.c",
    "rtos_tasks.c",
    "scrubber.c",
    "stubs.c",
    "thread.c",
    "virtio.c",
    "virtio_console.c",
    "watchdog.c",
]

objects = [env.Object(source) for source in sources]

Return('objects')
